export const repositoryConfig = {
  database: 'DATABASE_CONNECTION',
  assunto: 'ASSUNTO_REPOSITORY',
  descritor: 'DESCRITOR_REPOSITORY',
  fonte: 'FONTE_REPOSITORY',
  grupoAcesso: 'GRUPO_ACESSO_REPOSITORY',
  interesse: 'INTERSSE_REPOSITORY',
  midia: 'MIDIA_REPOSITORY',
  noticia: 'NOTICIA_REPOSITORY',
  tipoFonte: 'TIPO_FONTE_REPOSITORY',
  tipoMidia: 'TIPO_MIDIA_REPOSITORY',
  usuario: 'USUARIO_REPOSITORY',
  rss: 'RSS_REPOSITORY',
  tweetInfo: 'TWEET_INFO_REPOSITORY',
  tweetParametrosBusca: 'TWEET_PARAMETROS_BUSCA_REPOSITORY',
};
